language: java
jdk:
  - oraclejdk8
script:
  ./gradlew checkstyleMain checkstyleTest findbugsMain findbugsTest pmdMain pmdTest test;
  ./gradlew build
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

